disabled_rules:
  - trailing_comma
  - function_body_length

included:
  - HongKongKeyboard
  - HongKongKeyboardApp
  - GoogleInputTools

identifier_name:
  excluded:
    - id
    - x
    - y
    - dx
    - dy
